apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: {{ .Values.orderService.service.port }}
      targetPort: 5001
  type: {{ .Values.orderService.service.type }}