apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: {{ .Values.productService.service.port }}
      targetPort: 5000
  type: {{ .Values.productService.service.type }}